spring:
  cloud:
    gateway:
      routes:
      - id: bin
        uri: http://httpbin.org:80
        predicates:
          - Path=/bin
        filters:
          - AddRequestHeader=Hello,Gateway
      - id: hello
        uri: http://localhost:9900
        predicates:
          - Path=/hello
        filters:
          - AddRequestHeader=Hello,Gateway
