server:
  port: 9080

spring:
  cloud:
    gateway:
      routes:
      - id: bin
        uri: http://httpbin.org
        predicates:
          - Path=/forms/post
      - id: hello
        uri: http://localhost:9060
        predicates:
          - Path=/hello

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,bean"

logging:
  level:
    org.springframework: DEBUG
