spring:
  cloud:
    gateway:
      routes:
      - id: bin
        uri: http://httpbin.org:80
      - id: hello
        uri: http://localhost:9090
        predicates:
          - Path=/hello

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
